---
# test with: ansible all -m command -a "ls /tmp" -i hosts
- hosts: all
  gather_facts: yes
  tasks:
  - name: "Create empty file"
    file:
      path: "/tmp/a_testing_new_hosts_for_secure_shell_connectivity"
      state: touch