---
# tasks file for django
- name: "clone Django API from Github repository"  
  ansible.builtin.git: 
    repo: "{{ git_repo }}"
    dest: "{{ install_dir }}"
    version: master
    force: yes 

- name: "install w/pip Django & Django Rest in VEnv "
  pip:
    virtualenv: "{{ install_dir }}/venv"
    name: 
      - django 
      - djangorestframework
    state: latest

- name: "install w/pip Django & Django Rest modules in VEnv "
  pip:
    virtualenv: "{{ install_dir }}/venv"
    requirements: "{{ install_dir }}/requirements.txt"
    state: latest

- name: "change Django host in config file"
  lineinfile: 
    path: "{{ install_dir }}/setup/settings.py"
    regexp: "ALLOWED_HOSTS"
    line: 'ALLOWED_HOSTS = ["*"]'