---
# tasks file for database
- name: "setting database config"
  shell: "{{ venv_activate_dir }}; python {{ install_dir }}/manage.py migrate"

- name: "loading database"
  shell: "{{ venv_activate_dir }}; python {{ install_dir }}/manage.py loaddata clientes.json"

- name: "run production server"
  shell: "{{ venv_activate_dir }}; nohup python {{ install_dir }}/manage.py runserver 0.0.0.0:8000 &"