---
# tasks file for django
- name: "use pip to install Django & Django Rest in VEnv"
  pip:
    virtualenv: "{{ install_dir }}/venv"
    name: 
      - django 
      - djangorestframework
    state: latest

- name: "checking for redundancy, registering project initial files"
  stat:
    path: "{{ install_dir }}/setup/settings.py"
  register: project

- name: "activate & place Django Configs in VEnv"
  shell: "{{ venv_activate_dir }}; django-admin startproject setup {{ install_dir }}"
  when: not project.stat.exists
  # ignore_errors: yes

- name: "change Django host in config file"
  lineinfile: 
    path: "{{ install_dir }}/setup/settings.py"
    regexp: "ALLOWED_HOSTS"
    line: 'ALLOWED_HOSTS = ["*"]'